export enum AccountType {
    ADMIN = 'ADMIN',
    GAMEHEAD = 'GAMEHEAD',
    FINANCEHEAD = 'FINANCEHEAD',
    SETTINGSHEAD = 'SETTINGSHEAD',
    ADDITIONALHEAD = 'ADDITIONALHEAD',
    SUPPORTHEAD = 'SUPPORTHEAD',
    AGENT = 'AGENT',
    USER = 'USER',
    DUMMYUSER = 'DUMMYUSER'
  }